### ISSUE TITLE
error in `[[path]].ts` file for Cloudflare Pages deployment

### ISSUE THREAD

**Issue by jsparkdev** [yusukebe/hono-remix-adapter#10]
When I run the development server without running the build command, I get an error in the `[[path]].ts` file, is there any way to fix this problem?

If I don't run the build command, the build folder won't be created, so is it mandatory to run the first one-time build command before starting the development server?

![a](https://github.com/user-attachments/assets/d7e21195-2069-457c-ad89-17684df3b27c)

**Comment by yusukebe** [comment]
Hi @jsparkdev 

> Is there any way to fix this problem?

No way. You have to run the build command before running `wrangler pages dev`. Basically, we have to develop it with the `dev` command using Vite, not `start` command which is `wrangler pages dev`.

**Comment by jsparkdev** [comment]
@yusukebe Understood, thank you!
