### ISSUE TITLE
#9 is not included in v0.2.1 release

### ISSUE THREAD

**Issue by takamichi** [yusukebe/hono-remix-adapter#11]
It appears that the changes made in #9 are not included in the v0.2.1 release.

https://www.npmjs.com/package/hono-remix-adapter/v/0.2.1?activeTab=code

<img width="500" alt="npm dist-remix-js" src="https://github.com/user-attachments/assets/86273034-3b5f-426e-985e-10b364cf5ef7">

**Comment by yusukebe** [comment]
Hi @takamichi 

Sorry! I forgot to build it before releasing it. Fixed and released the new version, v0.2.2. Thanks!

**Comment by takamichi** [comment]
Thank you for the fix release 👍
