### ISSUE TITLE
Workers + assets instead of cloudflare pages

### ISSUE THREAD

**Issue by scttcper** [yusukebe/hono-remix-adapter#14]
Thanks for making this project, I made a small example of how to adopt this for workers w/ assets instead of cloudflare pages but i think there's likely more that could be done. Would be nice to be able to test scheduled workers without a different command.

[example](https://github.com/scttcper/remix-hono-worker)

**Comment by saaskitten** [comment]
@scttcper Doesn't [this](https://hono.dev/docs/getting-started/cloudflare-workers#using-hono-with-other-event-handlers) provide what you need?

**Comment by yusukebe** [comment]
Regarding templates for Workers, we can wait for the Remix-side. For instance, they have this PR: https://github.com/remix-run/remix/pull/10034

> i think there's likely more that could be done.

Yeah, we can find them. This page shows the difference between Pages and Workers which we can refer.
https://developers.cloudflare.com/workers/static-assets/compatibility-matrix/

**Comment by scttcper** [comment]
@yusukebe https://github.com/remix-run/remix/pull/10034 is exactly what i'm looking for. Thanks!
