### ISSUE TITLE
Question: Why is it not possible to use `Context` from hono in `getLoadContext` ?

### ISSUE THREAD

**Issue by ogadra** [yusukebe/hono-remix-adapter#23]
I reviewed the `createGetLoadContextArgs` function in src/remix.ts.
It creates the argument for `getLoadContext` using hono's `context`.
I believe it would be more practical if the argument of the `getLoadContext` function were directly hono's context. That way, we could leverage Hono's middleware in Remix.
However, this is not how it works in practice. I assume there must be a reason for this. Could you explain why?

**Comment by yusukebe** [comment]
> Could you explain why?

There is no reason. Just not implemented, but like this? #24

**Comment by ogadra** [comment]
Thanks. I'll check it later.
