### ISSUE TITLE
Question: Is this adapter supposed to work outside of Cloudflare?

### ISSUE THREAD

**Issue by john-griffin** [yusukebe/hono-remix-adapter#25]
I tried the adapter out on a local node project but got a few errors around missing `@remix-run/cloudflare`. Does the adapter have compatibility outside of Cloudflare environments too?

**Comment by yusukebe** [comment]
Hi @john-griffin 

Currently, it does not support Node.js. I'll work to support this adapter with Node.js.

**Comment by john-griffin** [comment]
@yusukebe thank you for clarifying, that would be great!!
