### ISSUE TITLE
Importing image assets 404s

### ISSUE THREAD

**Issue by john-griffin** [yusukebe/hono-remix-adapter#44]
When I try to import image assets from the public directory using normal vite syntax I get a 404 on the `?import` requests when using with hono-remix-adapter. 

Please see minimal reproduction below where I have switched the included Remix image files in a generated app to be imported eg `import logoLight from '/logo-light.png';`

https://stackblitz.com/edit/remix-run-remix-ug68cy?file=app%2Froutes%2F_index.tsx

Removing hono-remix-adapter from the vite config fixes it.

**Comment by yusukebe** [comment]
Hi @john-griffin 

Thank you for the issue. It's a known issue, but it should be fixed. I'll consider it.

**Comment by yusukebe** [comment]
Hi @john-griffin 

I've released the new version `0.5.4` including the fix. Can you try it?

**Comment by john-griffin** [comment]
Thanks, thats working!
