### ISSUE TITLE
Allow users to supply their own getLoadContext

### ISSUE THREAD

**Issue by jfsiii** [yusukebe/hono-remix-adapter#5]
According to [the Remix docs](https://remix.run/docs/en/main/guides/vite#augmenting-load-context):

> If you'd like to add additional properties to the load context, you should export a getLoadContext function from a shared module so that load context in Vite, Wrangler, and Cloudflare Pages are all augmented in the same way:

However, 

```ts
import handle from 'hono-remix-adapter/cloudflare-pages';
```

calls Remix with its own handler; not allowing the user to supply one

https://github.com/yusukebe/hono-remix-adapter/blob/4ad68d024236094042c614e485b913a541366836/src/cloudflare-pages.ts#L18-L28

This is a key bit of functionality. It'd be great if `handle` accepted another argument, or some other change was made so a user could supply their own `getLoadContext`

This is the expected type for the function

```ts
type GetLoadContext = (args: {
  request: Request;
  context: { cloudflare: Cloudflare }; // load context _before_ augmentation
}) => AppLoadContext;
```

**Comment by yusukebe** [comment]
Hi @jfsiii 

This is just an imaginary implementation but like this? I don't know if this API is good, but I may add the feature.

```ts
// functions/[[path]].ts
import handle from 'hono-remix-adapter/cloudflare-pages'
import * as build from '../build/server'
import server from '../server'

export const onRequest = handle(build, server, {
  extra: 'stuff', // You can pass extra values
})
```

**Comment by jfsiii** [comment]
Thanks for the quick response.

I think the handler needs to accept  the shared `getLoadContext` function, like this:

```tsx
// functions/[[path]].ts
import handle from 'hono-remix-adapter/cloudflare-pages'
import * as build from '../build/server'
import server from '../server'
import { getLoadContext } from '../load-context';

export const onRequest = handle(build, server, getLoadContext)
```

That's how the [current Pages request handler](https://remix.run/docs/en/main/guides/vite#augmenting-load-context) does it

```ts
import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server";
import { getLoadContext } from "../load-context";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext,
});
```

Then https://github.com/yusukebe/hono-remix-adapter/blob/4ad68d024236094042c614e485b913a541366836/src/cloudflare-pages.ts#L18-L28 would become

```ts
      return remix({
        build: serverBuild,
        mode: 'production',
        getLoadContext(c2) {
          // getLoadContext2 is the user-supplied function. The 3rd argument to `handler`
          return getLoadContext2({
            request: c2.req.raw,
            context: {
              cloudflare: {
                env: c2.env,
              },
            },
          });
        },
```

The signature for the `getLoadContext` function is

```ts
type GetLoadContext = (args: {
  request: Request;
  context: { cloudflare: Cloudflare }; // load context _before_ augmentation
}) => AppLoadContext;
```

Where `Cloudflare` is
```ts
import type { PlatformProxy } from 'wrangler';

// Env is the Wrangler Env. The interface from worker-configuration.d.ts
type Cloudflare = Omit<PlatformProxy<Env>, 'dispose'>;
```

When I hover that type in my IDE, I get

```ts
type Cloudflare = {
    env: Env2;
    cf: IncomingRequestCfProperties;
    ctx: ExecutionContext;
    caches: CacheStorage_2;
}
```

so, when handle passes
```

            context: {
              cloudflare: {
                env: c2.env,
              },
            }
```

That's not the full `Cloudflare` type, but it got me moving. Perhaps, the other items could be added as well for better/full compliance.

I'm happy to submit/review a PR as well if that's helpful.

Thanks, again!
